apiVersion: v1
kind: Service
metadata:
  name: device-api-service
  namespace: prod
spec:
  selector:
    app: device-api-service
  ports:
    - port: 3000
      targetPort: 3000
      name: device-api-service
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-api-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-api-service
  template:
    metadata:
      labels:
        app: device-api-service
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: device-api-service
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          env:
            - name: KAFKA_PREFIX
              value: prod
            - name: KAFKA_HOST
              value: kafka.kafka
            - name: KAFKA_PORT
              value: "9094"
          envFrom:
            - secretRef:
                name: device-api-prod
                optional: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: device-api
  namespace: prod
spec:
  rules:
    - host: device-api.116.203.237.159.xip.io
      http:
        paths:
          - backend:
              serviceName: device-api-service
              servicePort: 3000
            path: /api
  tls:
    - hosts:
        - device-api.116.203.237.159.xip.io
